version: '3'
services:

  #Apache Service
  webserver:
    image: httpd
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: fcuk
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./build/my.cnf:/etc/mysql/my.cnf
      - ./build/mysql/:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local